<?php
/**
 * One-time installer: writes app/config.php, creates tables + starting menu, creates the first admin.
 * Locks itself once an admin account exists.
 */
define('PS_INSTALLER', true);
require dirname(__DIR__) . '/app/bootstrap.php';

send_security_headers();
header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: no-store');
header('X-Robots-Tag: noindex');

$configFile = PS_APPDIR . '/config.php';
$hasConfig = is_file($configFile);
$errors = [];
$done = false;
$manualConfig = null;

// Installer CSRF: plain double-submit cookie (no app key exists yet).
$seed = $_COOKIE['ps_install'] ?? '';
if (!is_string($seed) || !preg_match('/^[a-f0-9]{32}$/', $seed)) {
    $seed = bin2hex(random_bytes(16));
    set_cookie('ps_install', $seed, 3600, ['samesite' => 'Strict', 'path' => '/install/']);
}

function admin_exists(): bool
{
    try {
        return (int) db()->query('SELECT COUNT(*) FROM admin_users')->fetchColumn() > 0;
    } catch (Throwable) {
        return false;
    }
}

if ($hasConfig && admin_exists()) {
    http_response_code(403);
    echo '<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Inštalácia</title>'
        . '<link rel="stylesheet" href="' . e(asset('/assets/css/site.css')) . '"><main class="wrap confirm"><div class="card confirm-card">'
        . '<h1>Inštalácia je hotová</h1><p>Web je nainštalovaný. Z bezpečnostných dôvodov môžete priečinok <code>install</code> zo servera zmazať.</p>'
        . '<div class="card-actions"><a class="btn btn-primary" href="/admin/">Administrácia</a><a class="btn btn-ghost" href="/">Web</a></div></div></main>';
    exit;
}

$v = [
    'db_host' => 'localhost', 'db_port' => '3306', 'db_name' => '', 'db_user' => '',
    'base_url' => base_url(), 'username' => 'admin',
];

if (is_post()) {
    foreach ($v as $k => $_) {
        $v[$k] = post_str($k, 200);
    }
    $dbPass = (string) ($_POST['db_pass'] ?? '');
    $pass = (string) ($_POST['password'] ?? '');
    $pass2 = (string) ($_POST['password2'] ?? '');

    if (!hash_equals($seed, (string) ($_POST['token'] ?? ''))) {
        $errors[] = 'Platnosť formulára vypršala, odošlite ho znova.';
    }
    if (!preg_match('/^[a-zA-Z0-9._-]{3,50}$/', $v['username'])) {
        $errors[] = 'Prihlasovacie meno: 3–50 znakov (písmená, čísla, bodka, pomlčka).';
    }
    if (strlen($pass) < 10) {
        $errors[] = 'Heslo musí mať aspoň 10 znakov.';
    } elseif ($pass !== $pass2) {
        $errors[] = 'Heslá sa nezhodujú.';
    }

    if (!$errors && !$hasConfig) {
        $v['base_url'] = rtrim($v['base_url'], '/');
        if (!preg_match('#^https?://[^/\s]+$#', $v['base_url'])) {
            $errors[] = 'Adresa webu musí byť v tvare https://www.vasadomena.sk (bez lomky na konci).';
        }
        if (!$errors) {
            try {
                db_connect($v['db_host'], (int) $v['db_port'], $v['db_name'], $v['db_user'], $dbPass);
            } catch (PDOException $e) {
                $errors[] = 'Nepodarilo sa pripojiť k databáze: ' . $e->getMessage();
            }
        }
        if (!$errors) {
            $config = [
                'db_host' => $v['db_host'],
                'db_port' => (int) $v['db_port'],
                'db_name' => $v['db_name'],
                'db_user' => $v['db_user'],
                'db_pass' => $dbPass,
                'base_url' => $v['base_url'],
                'app_key' => base64_encode(random_bytes(32)),
                'debug' => false,
            ];
            $php = "<?php\n// Generated by /install on " . date('Y-m-d H:i') . ". Keep secret – never commit or share.\n"
                . "// app_key encrypts customer data: if you lose it, stored contact details cannot be read.\nreturn "
                . var_export($config, true) . ";\n";
            if (@file_put_contents($configFile, $php, LOCK_EX) === false) {
                $manualConfig = $php;
            } else {
                @chmod($configFile, 0640);
            }
            $GLOBALS['PS_CONFIG'] = $config;
        }
    } elseif (!$errors) {
        $GLOBALS['PS_CONFIG'] = require $configFile;
    }

    if (!$errors && $manualConfig === null) {
        try {
            $pdo = db();
            db_run_sql_file($pdo, PS_APPDIR . '/sql/schema.sql');
            db_migrate($pdo, 1);
            if ((int) $pdo->query('SELECT COUNT(*) FROM categories')->fetchColumn() === 0) {
                db_run_sql_file($pdo, PS_APPDIR . '/sql/seed.sql');
            }
            if (!admin_exists()) {
                $pdo->prepare('INSERT INTO admin_users (username, password_hash, created_at) VALUES (?, ?, ?)')
                    ->execute([$v['username'], password_hash($pass, PASSWORD_DEFAULT), now_str()]);
            }
            $done = true;
        } catch (Throwable $e) {
            $errors[] = 'Chyba pri vytváraní tabuliek: ' . $e->getMessage();
        }
    }
}
?>
<!doctype html>
<html lang="sk">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Inštalácia – Pizza Slice</title>
<link rel="stylesheet" href="<?= e(asset('/assets/css/site.css')) ?>">
</head>
<body>
<main class="wrap confirm">
  <div class="card confirm-card">
    <img src="/assets/img/logo-208.webp" width="104" height="95" alt="">
    <p class="eyebrow">Inštalácia</p>
    <?php if ($done): ?>
      <h1>Hotovo!</h1>
      <p>Databáza je pripravená, menu je naplnené a administrátorský účet <b><?= e($v['username']) ?></b> je vytvorený.</p>
      <ol>
        <li>Otvorte <a href="/admin/">/admin/</a>, prihláste sa a v <b>Nastaveniach</b> doplňte adresu, telefón a údaje firmy.</li>
        <li>Na mobile otvorte /admin/ a pridajte si aplikáciu na plochu (Android: „Inštalovať aplikáciu“, iPhone: Zdieľať → „Pridať na plochu“).</li>
        <li>Priečinok <code>install</code> môžete zo servera zmazať.</li>
      </ol>
      <div class="card-actions"><a class="btn btn-primary" href="/admin/">Do administrácie</a><a class="btn btn-ghost" href="/">Pozrieť web</a></div>
    <?php elseif ($manualConfig !== null): ?>
      <h1>Uložte konfiguráciu ručne</h1>
      <p>Server nedovolil zapísať súbor <code>app/config.php</code>. Vytvorte ho cez FTP s týmto obsahom a potom tento formulár odošlite znova:</p>
      <textarea class="input" rows="14" readonly><?= e($manualConfig) ?></textarea>
    <?php else: ?>
      <h1>Nastavenie webu</h1>
      <?php foreach ($errors as $err): ?><p class="notice notice-err"><?= e($err) ?></p><?php endforeach; ?>
      <form method="post" class="form" autocomplete="off">
        <input type="hidden" name="token" value="<?= e($seed) ?>">
        <?php if (!$hasConfig): ?>
        <h2>Databáza MariaDB</h2>
        <p class="fineprint">Údaje nájdete v administrácii WebSupport → Databázy.</p>
        <div class="field"><label for="i-host">Server (host)</label><input class="input" id="i-host" name="db_host" required value="<?= e($v['db_host']) ?>"></div>
        <div class="field"><label for="i-port">Port</label><input class="input" id="i-port" name="db_port" inputmode="numeric" required value="<?= e($v['db_port']) ?>"></div>
        <div class="field"><label for="i-name">Názov databázy</label><input class="input" id="i-name" name="db_name" required value="<?= e($v['db_name']) ?>"></div>
        <div class="field"><label for="i-user">Používateľ</label><input class="input" id="i-user" name="db_user" required value="<?= e($v['db_user']) ?>"></div>
        <div class="field"><label for="i-pass">Heslo k databáze</label><input class="input" id="i-pass" name="db_pass" type="password"></div>
        <div class="field"><label for="i-url">Adresa webu</label><input class="input" id="i-url" name="base_url" type="url" required value="<?= e($v['base_url']) ?>"></div>
        <?php endif; ?>
        <h2>Administrátor</h2>
        <div class="field"><label for="i-u">Prihlasovacie meno</label><input class="input" id="i-u" name="username" required autocomplete="username" value="<?= e($v['username']) ?>"></div>
        <div class="field"><label for="i-p">Heslo (min. 10 znakov)</label><input class="input" id="i-p" name="password" type="password" required minlength="10" autocomplete="new-password"></div>
        <div class="field"><label for="i-p2">Heslo znova</label><input class="input" id="i-p2" name="password2" type="password" required minlength="10" autocomplete="new-password"></div>
        <button class="btn btn-primary btn-lg btn-block" type="submit">Nainštalovať</button>
      </form>
    <?php endif; ?>
  </div>
</main>
</body>
</html>
